sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t number1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true number1/react-test npm test

after_success:
  - docker build -t number1/multi-client ./client
  - docker build -t number1/multi-nginx ./nginx
  - docker build -t number1/multi-server ./server
  - docker build -t number1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push number1/multi-client
  - docker push number1/multi-nginx
  - docker push number1/multi-server
  - docker push number1/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-923445559289"
#   bucket_path: "docker-multi"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
